import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Login from "./login";
import Shopping from "./shopping";
import { useSelector, useDispatch } from "react-redux";
import { showNotification } from "../slices/ui-slice";
import Notification from "../component/notification";
import { useEffect, useRef } from "react";

export default function Home() {
  const isFirstRender = useRef(true);
  const isLoggedIn = useSelector((state) => state.auth.isLoggedIn);
  console.log(isLoggedIn);

  const notification = useSelector((state) => state.ui.notification);

  const cart = useSelector((state) => state.cart);

  const dispatch = useDispatch();
  useEffect(() => {
    const sendReq = async () => {
      dispatch(
        showNotification({
          open: true,
          message: "Sending Request",
          type: "warning",
        })
      );
      const res = await fetch(
        process.env.NEXT_PUBLIC_REALTIME_FIREBASE_URL + "cartItems.json",
        {
          method: "PUT",
          body: JSON.stringify(cart),
        }
      );
      const data = res.json();
      dispatch(
        showNotification({
          open: true,
          message: "Sending Request Successfully",
          type: "success",
        })
      );
    };
    console.log(cart);
    if (cart.itemList.length > 0) {
      sendReq().catch((err) => {
        dispatch(
          showNotification({
            open: true,
            message: "Sending Request Failed",
            type: "error",
          })
        );
      });
    }
  }, [cart]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      {notification && (
        <Notification type={notification.type} message={notification.message} />
      )}
      {!isLoggedIn && <Login />}
      {isLoggedIn && <Shopping />}
    </div>
  );
}
