import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Login from "./login";
import Shopping from "./shopping";
import { useSelector } from "react-redux";
export default function Home() {
  const isLoggedIn = useSelector((state) => state.auth.isLoggedIn);
  console.log(isLoggedIn);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isLoggedIn && <Login />}
      {isLoggedIn && <Shopping />}
    </div>
  );
}
